const dados = {
  "estado": "SP",
  "cidades": [
    "VOTORANTIM",
    "TORRE DE PEDRA",
    "TIETÊ",
    "TATUÍ",
    "TAQUARIVAÍ",
    "TAPIRAÍ",
    "SOROCABA",
    "SARAPUÍ",
    "SÃO MIGUEL ARCANJO",
    "SALTO DE PIRAPORA",
    "RIVERSUL",
    "RIBEIRÃO GRANDE",
    "RIBEIRÃO BRANCO",
    "RIBEIRA",
    "QUADRA",
    "PORTO FELIZ",
    "PORANGABA",
    "PILAR DO SUL",
    "PIEDADE",
    "NOVA CAMPINA",
    "LARANJAL PAULISTA",
    "JUMIRIM",
    "ITARARÉ",
    "ITAPORANGA",
    "ITAPIRAPUÃ PAULISTA",
    "ITAPEVA",
    "ITAPETININGA",
    "ITAÓCA",
    "ITABERÁ",
    "IPORANGA",
    "IPERÓ",
    "IBIÚNA",
    "GUAREÍ",
    "GUAPIARA",
    "CESÁRIO LANGE",
    "CERQUILHO",
    "CAPELA DO ALTO",
    "CAPÃO BONITO",
    "CAMPINA DO MONTE ALEGRE",
    "BURI",
    "BOM SUCESSO DE ITARARÉ",
    "BOITUVA",
    "BARRA DO TURVO",
    "BARRA DO CHAPÉU",
    "BARÃO DE ANTONINA",
    "ARAÇOIABA DA SERRA",
    "APIAÍ",
    "ANGATUBA",
    "ALAMBARI"
  ]
}

export default dados;